apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: PLACEHOLDER_AZURE_CONTAINER_REGISTRY.azurecr.io/as6-2_osso_frontend:main
        ports:
        - containerPort: 3000
        env:
          - name: AUTH_AUTH0_ID
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH0_ID
          - name: AUTH_AUTH0_SECRET
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTH0_SECRET
          - name: AUTH_AUTH0_ISSUER
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTHJS_SECRET
          - name: AUTH_AUTH0_AUDIENCE
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTHJS_SECRET
          - name: AUTH_SECRET
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AUTHJS_SECRET
          - name: GATEWAY_URL
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: GATEWAY_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
